### ISSUE TITLE
Missing or Incorrect Image Paths for Hero Section and Shop Section

### ISSUE THREAD

**Issue by shubhamsharma9199** [AbhishekChamp879/Amazon_clone_Frontend#1]
Some images in the hero-section and shop-section are not loading properly. This is because the image paths appear to be incorrect or the images might be missing from the specified locations (e.g., hero\ image2.jpg, healthcare.jpeg, pic16.jpg, etc.).can you assign me to slove the issue @AbhishekChamp879

**Comment by shubhamsharma9199** [comment]
Please label this issue as 'Hacktoberfest Accepted. @AbhishekChamp879

**Comment by AbhishekChamp879** [comment]
Hi, thanks for raising this issue! Just a quick clarification: the hacktoberfest-accepted label is applied to pull requests (PRs) after they've been reviewed and approved, not to issues. Please feel free to submit a PR for this issue, and once it's successfully reviewed, I'll be happy to add the label.

**Comment by BaniSinghgithub** [comment]
I am very keen to work on it , pls assign it to me
