### ISSUE TITLE
In this project security policy is not  present if we compare it to the original amazon website.

### ISSUE THREAD

**Issue by urbruder** [AbhishekChamp879/Amazon_clone_Frontend#16]
In this project security policy is not  present if we compare it to the original amazon website. I have added the security policy part.
Before:
![Screenshot (16)](https://github.com/user-attachments/assets/d07d2095-620e-4b8b-b0ee-b1909056704e)

**Comment by BaniSinghgithub** [comment]
@AbhishekChamp879 , pls assign this task to me
