### ISSUE TITLE
Implement more options in the navbar

### ISSUE THREAD

**Issue by urbruder** [AbhishekChamp879/Amazon_clone_Frontend#3]
In the panel section like electronics, mobiles ,home and kitchen and prime is missing if we compare it with original Amazon Website. I  will be adding these options in the panel sections.
![Screenshot (3)](https://github.com/user-attachments/assets/80183587-ba40-49be-88bf-0ff878d5b4c6)

**Comment by AbhishekChamp879** [comment]
Hi, thanks for raising this issue! Just a quick clarification: the hacktoberfest-accepted label is applied to pull requests (PRs) after they've been reviewed and approved, not to issues. Please feel free to submit a PR for this issue, and once it's successfully reviewed, I'll be happy to add the label. Happy contribution @urbruder

**Comment by Naumantamboli** [comment]
hey!, can i work on this issue?

**Comment by Vidyut18** [comment]
Hello abhishek! Shall i too work on this issue?

**Comment by AbhishekChamp879** [comment]
Hey contributors kindly raise another issues. As this issue is already assign to someone else. So if you are interested, feel free to raise issues, suggest improvements, bugs ..Collaboration is always welcome, and we can find a way to work together! @Vidyut18 @Naumantamboli

**Comment by BaniSinghgithub** [comment]
hello @AbhishekChamp879 , pls assign it to me
